#!/usr/bin/env node
// Halyard icons: validates every icons/*.svg against the icon rules and generates src/icons.ts.
// Rules: well-formed XML, single <svg> root, viewBox "0 0 20 20", stroke="currentColor",
// stroke-width 1.5, round caps/joins, no hard-coded colours, fills only "none" or "currentColor"
// (filled shapes are allowed only as dots: <circle r <= 1.6>).
// Usage: node scripts/build-icons.mjs          (validate + write src/icons.ts)
//        node scripts/build-icons.mjs --check  (validate + fail if src/icons.ts is stale)
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconDir = join(root, 'icons');
const outFile = join(root, 'src', 'icons.ts');
const check = process.argv.includes('--check');

/** Minimal XML tokenizer: returns elements as {name, attrs, selfClosing} and asserts balance. */
function parse(src, file) {
  const els = [];
  const stack = [];
  const re = /<(\/?)([a-zA-Z][\w:-]*)((?:\s+[\w:-]+="[^"<>]*")*)\s*(\/?)>/g;
  let last = 0;
  let m;
  while ((m = re.exec(src))) {
    const between = src.slice(last, m.index);
    if (between.trim() !== '') throw new Error(`${file}: unexpected text "${between.trim().slice(0, 30)}"`);
    last = re.lastIndex;
    const [, close, name, rawAttrs, self] = m;
    if (close) {
      const open = stack.pop();
      if (open !== name) throw new Error(`${file}: </${name}> closes <${open ?? 'nothing'}>`);
      continue;
    }
    const attrs = {};
    for (const a of rawAttrs.matchAll(/([\w:-]+)="([^"]*)"/g)) {
      if (a[1] in attrs) throw new Error(`${file}: duplicate attribute ${a[1]} on <${name}>`);
      attrs[a[1]] = a[2];
    }
    if (stack.length === 0 && els.length > 0) throw new Error(`${file}: multiple root elements`);
    els.push({ name, attrs, depth: stack.length });
    if (!self) stack.push(name);
  }
  if (src.slice(last).trim() !== '') throw new Error(`${file}: trailing content`);
  if (stack.length) throw new Error(`${file}: unclosed <${stack.join('>, <')}>`);
  if (!els.length) throw new Error(`${file}: empty`);
  return els;
}

const ALLOWED = new Set(['svg', 'path', 'circle', 'rect', 'line', 'polyline', 'polygon', 'ellipse', 'g']);
function validate(src, file) {
  const els = parse(src, file);
  const [svg] = els;
  const errs = [];
  if (svg.name !== 'svg') errs.push('root is not <svg>');
  const want = {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 20 20',
    fill: 'none',
    stroke: 'currentColor',
    'stroke-width': '1.5',
    'stroke-linecap': 'round',
    'stroke-linejoin': 'round',
  };
  for (const [k, v] of Object.entries(want))
    if (svg.attrs[k] !== v) errs.push(`<svg ${k}="${svg.attrs[k]}"> expected "${v}"`);
  if ('width' in svg.attrs || 'height' in svg.attrs)
    errs.push('<svg> must not set width/height (size via CSS)');
  for (const el of els.slice(1)) {
    if (!ALLOWED.has(el.name)) errs.push(`disallowed element <${el.name}>`);
    for (const [k, v] of Object.entries(el.attrs)) {
      if (/^(fill|stroke|color|stop-color)$/.test(k) && !['none', 'currentColor'].includes(v))
        errs.push(`<${el.name} ${k}="${v}"> hard-coded colour`);
      if (k === 'style' || k === 'class' || k === 'id' || k.startsWith('on'))
        errs.push(`<${el.name}> attribute ${k} not allowed`);
      if (k === 'stroke-width') errs.push(`<${el.name}> overrides stroke-width`);
    }
    if (el.attrs.fill === 'currentColor' && !(el.name === 'circle' && Number(el.attrs.r) <= 1.6))
      errs.push(`<${el.name}> filled shape that is not a dot (circle r<=1.6)`);
  }
  if (!src.includes('currentColor')) errs.push('does not use currentColor');
  if (errs.length) throw new Error(`${file}:\n  ${errs.join('\n  ')}`);
}

const files = readdirSync(iconDir)
  .filter((f) => f.endsWith('.svg'))
  .sort();
const failures = [];
const entries = [];
for (const f of files) {
  const name = f.slice(0, -4);
  if (!/^[a-z][a-z0-9-]*$/.test(name)) failures.push(`${f}: name must be kebab-case`);
  const src = readFileSync(join(iconDir, f), 'utf8').trim();
  try {
    validate(src, f);
    entries.push([name, src]);
  } catch (e) {
    failures.push(e.message);
  }
}
if (failures.length) {
  console.error(`icon validation failed (${failures.length}):\n${failures.join('\n')}`);
  process.exit(1);
}

const raw = [
  '// GENERATED by scripts/build-icons.mjs from icons/*.svg. Do not edit by hand.',
  '/** Halyard icon set: 20x20, 1.5 stroke, round caps, currentColor. Inline as innerHTML or a data URI. */',
  'export const icons = {',
  ...entries.map(([n, s]) => `  ${/^[a-z]+$/.test(n) ? n : `'${n}'`}: '${s}',`),
  '} as const;',
  'export type IconName = keyof typeof icons;',
  'export const ICON_NAMES = Object.keys(icons) as IconName[];',
  '',
].join('\n');
// Format with the repo's prettier config so `--check` and `prettier --check` agree.
const prettier = await import('prettier');
const body = await prettier.format(raw, { ...(await prettier.resolveConfig(outFile)), filepath: outFile });
if (entries.some(([, s]) => s.includes("'"))) throw new Error('icon source contains a single quote');

if (check) {
  const cur = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
  if (cur !== body) {
    console.error('src/icons.ts is stale: run node packages/ui/scripts/build-icons.mjs');
    process.exit(1);
  }
  console.log(`${entries.length} icons valid; src/icons.ts up to date.`);
} else {
  writeFileSync(outFile, body);
  console.log(`${entries.length} icons valid; wrote src/icons.ts.`);
}
