'use client';
import { useEffect, useRef, useState } from 'react';

interface Island {
  mount(
    el: HTMLElement,
    opts: { seed?: number; projects?: number; interactive?: boolean; onReady?: () => void },
  ): { unmount(): void };
}

type Why = 'pending' | 'live' | 'reduced' | 'no-webgl' | 'error' | 'save-data';
type Theme = 'light' | 'dark';

/** Poster widths generated by scripts/assets.mjs: public/poster/fleet-<theme>-<w>.webp */
const POSTER_WIDTHS = [768, 1280, 1920] as const;
const srcSet = (t: Theme) => POSTER_WIDTHS.map((w) => `/poster/fleet-${t}-${w}.webp ${w}w`).join(', ');
/** Square 840px phone poster (scripts/assets.mjs: public/poster/fleet-<theme>-m.webp). */
const phonePoster = (t: Theme) => `/poster/fleet-${t}-m.webp`;

/**
 * The scene follows html[data-theme], else the system scheme. The <picture> covers the system case
 * with no script; an explicit toggle that disagrees with the system swaps the poster after hydration.
 */
function useForcedTheme(): Theme | null {
  const [forced, setForced] = useState<Theme | null>(null);
  useEffect(() => {
    const root = document.documentElement;
    const read = () => {
      const t = root.getAttribute('data-theme');
      setForced(t === 'light' || t === 'dark' ? t : null);
    };
    read();
    const mo = new MutationObserver(read);
    mo.observe(root, { attributes: true, attributeFilter: ['data-theme'] });
    return () => mo.disconnect();
  }, []);
  return forced;
}

function webglAvailable(): boolean {
  try {
    const c = document.createElement('canvas');
    return Boolean(c.getContext('webgl2') ?? c.getContext('webgl'));
  } catch {
    return false;
  }
}

/** Waits for load + idle so the scene never competes with LCP (the poster is the LCP element). */
function afterLcp(cb: () => void): () => void {
  let cancelled = false;
  let idle = 0;
  const run = () => {
    if (cancelled) return;
    const ric = (
      window as Window & { requestIdleCallback?: (f: () => void, o?: { timeout: number }) => number }
    ).requestIdleCallback;
    if (ric) idle = ric(() => !cancelled && cb(), { timeout: 2500 });
    else idle = window.setTimeout(() => !cancelled && cb(), 600);
  };
  // Phones and touch devices: the WebGL boot costs seconds of main thread on a mid-range CPU, so the poster
  // stays until the visitor first touches, scrolls with a key or clicks. Desktop starts on idle after load.
  const lazy = window.matchMedia('(max-width: 720px), (pointer: coarse)').matches;
  const INTERACT = ['pointerdown', 'touchstart', 'keydown', 'wheel'] as const;
  const onInteract = () => {
    for (const t of INTERACT) window.removeEventListener(t, onInteract);
    run();
  };
  if (lazy) for (const t of INTERACT) window.addEventListener(t, onInteract, { once: true, passive: true });
  else if (document.readyState === 'complete') run();
  else window.addEventListener('load', run, { once: true });
  return () => {
    cancelled = true;
    for (const t of INTERACT) window.removeEventListener(t, onInteract);
    window.removeEventListener('load', run);
    window.clearTimeout(idle);
    (window as Window & { cancelIdleCallback?: (h: number) => void }).cancelIdleCallback?.(idle);
  };
}

/**
 * The real Fleet visualizer over a poster. The poster is a still render of the same scene.
 * Reduced motion, Save-Data or no WebGL keep the poster. The island (public/island/fleet-scene.js)
 * is the FleetScene from packages/web driven by createDemoFleet: synthetic data, no network.
 */
export function FleetStage({
  posterAlt,
  interactive = false,
  seed = 7,
  projects,
  onState,
}: {
  posterAlt: string;
  interactive?: boolean;
  seed?: number;
  projects?: number;
  onState?: (why: Why) => void;
}) {
  const host = useRef<HTMLDivElement>(null);
  const [ready, setReady] = useState(false);
  const [why, setWhy] = useState<Why>('pending');
  const forced = useForcedTheme();

  useEffect(() => onState?.(why), [why, onState]);

  useEffect(() => {
    const el = host.current;
    if (!el) return;
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    const conn = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection;
    if (mq.matches) return setWhy('reduced');
    if (conn?.saveData && !interactive) return setWhy('save-data');
    if (!webglAvailable()) return setWhy('no-webgl');
    let handle: { unmount(): void } | null = null;
    let disposed = false;
    // `disposed` covers unmount; reduced motion is re-read at every step because it can switch on while the
    // startup is still waiting for idle/interaction or while the island module is downloading.
    const start = () => {
      if (disposed || mq.matches) return;
      import(/* webpackIgnore: true */ '/island/fleet-scene.js' as string)
        .then((mod: Island) => {
          if (disposed || mq.matches) return;
          handle = mod.mount(el, {
            seed,
            projects,
            interactive,
            onReady: () => {
              if (!disposed) {
                setReady(true);
                setWhy('live');
              }
            },
          });
        })
        .catch(() => !disposed && !mq.matches && setWhy('error'));
    };
    const cancel = interactive ? (start(), () => undefined) : afterLcp(start);
    const onChange = () => {
      if (mq.matches) {
        cancel();
        handle?.unmount();
        handle = null;
        setReady(false);
        setWhy('reduced');
      }
    };
    mq.addEventListener('change', onChange);
    return () => {
      disposed = true;
      cancel();
      mq.removeEventListener('change', onChange);
      handle?.unmount();
    };
  }, [interactive, seed, projects]);

  return (
    <>
      <picture>
        {/* Phones get a square still rendered at phone size, so its station labels stay legible. */}
        {forced ? null : (
          <source
            media="(max-width: 720px) and (prefers-color-scheme: light)"
            srcSet={phonePoster('light')}
          />
        )}
        <source media="(max-width: 720px)" srcSet={phonePoster(forced ?? 'dark')} />
        {forced ? null : (
          <source media="(prefers-color-scheme: light)" srcSet={srcSet('light')} sizes="100vw" />
        )}
        <img
          className="hero-poster"
          src={`/poster/fleet-${forced ?? 'dark'}-1920.webp`}
          srcSet={srcSet(forced ?? 'dark')}
          sizes="100vw"
          alt={posterAlt}
          fetchPriority="high"
          decoding="async"
          width={1920}
          height={1080}
          aria-hidden={ready ? true : undefined}
        />
      </picture>
      <div ref={host} className="hero-live" data-ready={ready} aria-hidden={!interactive} />
    </>
  );
}
