'use client';
import { useEffect, useRef, useState } from 'react';
import anchors from '@/lib/poster-anchors.json';
import world from '@/lib/world.generated.json';

interface Island {
  mount(
    el: HTMLElement,
    opts: {
      world?: { seed: number; now: number };
      interactive?: boolean;
      frame?: boolean;
      onReady?: () => void;
    },
  ): { unmount(): void };
}

type Why = 'pending' | 'live' | 'reduced' | 'no-webgl' | 'error' | 'save-data';
type Theme = 'light' | 'dark';

/** Poster widths generated by scripts/assets.mjs: public/poster/fleet-<theme>-<w>.webp */
const POSTER_WIDTHS = [768, 1280, 1920] as const;
const srcSet = (t: Theme) => POSTER_WIDTHS.map((w) => `/poster/fleet-${t}-${w}.webp ${w}w`).join(', ');
/** Square 840px phone poster (scripts/assets.mjs: public/poster/fleet-<theme>-m.webp). */
const phonePoster = (t: Theme) => `/poster/fleet-${t}-m.webp`;
/** Mirrors the <picture> sources below for a visitor on the system scheme (the common case and Lighthouse's). */
const POSTER_PRELOADS = (['light', 'dark'] as const).flatMap((t) => [
  { media: `(max-width: 720px) and (prefers-color-scheme: ${t})`, href: phonePoster(t) },
  { media: `(min-width: 721px) and (prefers-color-scheme: ${t})`, srcSet: srcSet(t) },
]);

/**
 * The scene follows html[data-theme], else the system scheme. The <picture> covers the system case
 * with no script; an explicit toggle that disagrees with the system swaps the poster after hydration.
 */
function useForcedTheme(): Theme | null {
  const [forced, setForced] = useState<Theme | null>(null);
  useEffect(() => {
    const root = document.documentElement;
    const read = () => {
      const t = root.getAttribute('data-theme');
      setForced(t === 'light' || t === 'dark' ? t : null);
    };
    read();
    const mo = new MutationObserver(read);
    mo.observe(root, { attributes: true, attributeFilter: ['data-theme'] });
    return () => mo.disconnect();
  }, []);
  return forced;
}

function webglAvailable(): boolean {
  try {
    const c = document.createElement('canvas');
    return Boolean(c.getContext('webgl2') ?? c.getContext('webgl'));
  } catch {
    return false;
  }
}

/** Waits for load + idle so the scene never competes with LCP (the poster is the LCP element). */
function afterLcp(cb: () => void): () => void {
  let cancelled = false;
  let idle = 0;
  const run = () => {
    if (cancelled) return;
    const ric = (
      window as Window & { requestIdleCallback?: (f: () => void, o?: { timeout: number }) => number }
    ).requestIdleCallback;
    if (ric) idle = ric(() => !cancelled && cb(), { timeout: 2500 });
    else idle = window.setTimeout(() => !cancelled && cb(), 600);
  };
  // Phones and touch devices: the WebGL boot costs seconds of main thread on a mid-range CPU, so the poster
  // stays until the visitor first touches, scrolls with a key or clicks. Desktop starts on idle after load.
  const lazy = window.matchMedia('(max-width: 720px), (pointer: coarse)').matches;
  const INTERACT = ['pointerdown', 'touchstart', 'keydown', 'wheel'] as const;
  const onInteract = () => {
    for (const t of INTERACT) window.removeEventListener(t, onInteract);
    run();
  };
  if (lazy) for (const t of INTERACT) window.addEventListener(t, onInteract, { once: true, passive: true });
  else if (document.readyState === 'complete') run();
  else window.addEventListener('load', run, { once: true });
  return () => {
    cancelled = true;
    for (const t of INTERACT) window.removeEventListener(t, onInteract);
    window.removeEventListener('load', run);
    window.clearTimeout(idle);
    (window as Window & { cancelIdleCallback?: (h: number) => void }).cancelIdleCallback?.(idle);
  };
}

/** Poster anchors as CSS custom properties: the stylesheet picks the pair for the poster on screen. */
const ANCHOR_VARS = Object.fromEntries(
  Object.entries(anchors).flatMap(([k, a]) => [
    [`--fx-${k}`, String(a.x)],
    [`--fy-${k}`, String(a.y)],
  ]),
) as React.CSSProperties;

/** Clearance (px) a station tag keeps from the hero copy. */
const KEEPOUT_PAD = 14;

/**
 * Keeps the scene's station tags out of the words: a tag whose text block would sit over a [data-keepout]
 * element of the section (eyebrow, headline, lead, meta row; for a [data-keepout="children"] row, each of its
 * items: install box, demo link) or in the top band under the header fades out (data-occluded, globals.css). The waiting station's tag is never hidden; the
 * camera framing keeps it clear. All reads happen before any write, so this costs one layout per frame.
 */
function keepLabelsClear(tags: HTMLElement[], section: Element, stage: DOMRect) {
  const zones = [
    ...section.querySelectorAll(
      '[data-keepout]:not([data-keepout="children"]), [data-keepout="children"] > *',
    ),
  ].map((el) => el.getBoundingClientRect());
  const band = stage.top + Math.min(80, stage.height * 0.14);
  const hits = tags.map((tag) => {
    if (tag.dataset.needs === '1') return false;
    const b = (tag.querySelector('.fl-viz-block') ?? tag).getBoundingClientRect();
    if (b.width === 0 && b.height === 0) return false;
    if (b.top < band) return true;
    return zones.some(
      (z) =>
        b.left < z.right + KEEPOUT_PAD &&
        b.right > z.left - KEEPOUT_PAD &&
        b.top < z.bottom + KEEPOUT_PAD &&
        b.bottom > z.top - KEEPOUT_PAD,
    );
  });
  tags.forEach((tag, i) => {
    const want = hits[i] ? '1' : undefined;
    if (tag.dataset.occluded !== want) {
      if (want) tag.dataset.occluded = want;
      else delete tag.dataset.occluded;
    }
  });
}

/**
 * Follows the live scene's waiting station: its tag anchor (the signal pennant), measured each frame in the
 * stage's own, untransformed coordinates and handed to the stylesheet, which frames it and raises the beacon.
 * No waiting station on screen: data-signal="none" (beacon down, frame eases back to the whole harbour).
 */
function trackSignal(stage: HTMLElement, frame: HTMLElement, host: HTMLElement): () => void {
  let raf = 0;
  let visible = true;
  let last = '';
  const io = new IntersectionObserver(([e]) => {
    visible = Boolean(e?.isIntersecting);
    if (visible && !raf) raf = requestAnimationFrame(step);
  });
  io.observe(stage);
  const section = stage.closest('section') ?? document.body;
  function step() {
    raf = 0;
    if (!visible) return;
    const tags = [...host.querySelectorAll<HTMLElement>('.fl-viz-tag')].filter(
      (el) => el.style.visibility !== 'hidden' && el.style.display !== 'none',
    );
    const tag = tags.find((el) => el.dataset.needs === '1');
    const sr = stage.getBoundingClientRect();
    const fr = frame.getBoundingClientRect();
    keepLabelsClear(tags, section, sr);
    if (tag && sr.width > 0 && fr.width > 0) {
      const z = fr.width / sr.width;
      const r = tag.getBoundingClientRect();
      const x = (r.left - fr.left) / z;
      const y = (r.bottom - fr.top) / z;
      stage.style.setProperty('--live-ax', `${x.toFixed(1)}px`);
      stage.style.setProperty('--live-ay', `${y.toFixed(1)}px`);
      if (last !== 'live') stage.dataset.signal = last = 'live';
    } else if (last !== 'none') stage.dataset.signal = last = 'none';
    raf = requestAnimationFrame(step);
  }
  raf = requestAnimationFrame(step);
  return () => {
    io.disconnect();
    cancelAnimationFrame(raf);
  };
}

/**
 * The real Fleet visualizer over a poster. The poster is a still render of the same scene.
 * Reduced motion, Save-Data or no WebGL keep the poster. The island (public/island/fleet-scene.js)
 * is the FleetScene from packages/web driven by the site's createDemoWorld fleet: synthetic data, no network, the site's
 * one world (lib/world.mjs). With `signal` (the home hero), a beacon rises from the waiting station and
 * phones frame that station; both come from the poster's recorded anchor first, then the live scene.
 */
export function FleetStage({
  posterAlt,
  interactive = false,
  signal = false,
  onState,
}: {
  posterAlt: string;
  interactive?: boolean;
  signal?: boolean;
  onState?: (why: Why) => void;
}) {
  const host = useRef<HTMLDivElement>(null);
  const stage = useRef<HTMLDivElement>(null);
  const frame = useRef<HTMLDivElement>(null);
  const [ready, setReady] = useState(false);
  const [why, setWhy] = useState<Why>('pending');
  const forced = useForcedTheme();

  useEffect(() => {
    const st = stage.current;
    const fr = frame.current;
    const el = host.current;
    if (!signal || !ready || !st || !fr || !el) return;
    const stop = trackSignal(st, fr, el);
    return () => {
      stop();
      st.dataset.signal = 'poster';
    };
  }, [signal, ready]);

  useEffect(() => onState?.(why), [why, onState]);

  useEffect(() => {
    const el = host.current;
    if (!el) return;
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    const conn = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection;
    if (mq.matches) return setWhy('reduced');
    if (conn?.saveData && !interactive) return setWhy('save-data');
    if (!webglAvailable()) return setWhy('no-webgl');
    let handle: { unmount(): void } | null = null;
    let disposed = false;
    // `disposed` covers unmount; reduced motion is re-read at every step because it can switch on while the
    // startup is still waiting for idle/interaction or while the island module is downloading.
    const start = () => {
      if (disposed || mq.matches) return;
      import(/* webpackIgnore: true */ '/island/fleet-scene.js' as string)
        .then((mod: Island) => {
          if (disposed || mq.matches) return;
          handle = mod.mount(el, {
            world,
            interactive,
            frame: signal,
            onReady: () => {
              if (!disposed) {
                setReady(true);
                setWhy('live');
              }
            },
          });
        })
        .catch(() => !disposed && !mq.matches && setWhy('error'));
    };
    const cancel = interactive ? (start(), () => undefined) : afterLcp(start);
    const onChange = () => {
      if (mq.matches) {
        cancel();
        handle?.unmount();
        handle = null;
        setReady(false);
        setWhy('reduced');
      }
    };
    mq.addEventListener('change', onChange);
    return () => {
      disposed = true;
      cancel();
      mq.removeEventListener('change', onChange);
      handle?.unmount();
    };
  }, [interactive, signal]);

  return (
    <>
      {/* The poster is the LCP element: fetch the one this viewport and scheme will show first, at high priority,
          from the head (React hoists these), before the fonts and scripts compete for the connection. */}
      {POSTER_PRELOADS.map((p) => (
        <link
          key={p.media}
          rel="preload"
          as="image"
          media={p.media}
          {...('href' in p ? { href: p.href } : { imageSrcSet: p.srcSet, imageSizes: '100vw' })}
          fetchPriority="high"
        />
      ))}
      <div
        ref={stage}
        className="stage"
        data-signal={signal ? 'poster' : undefined}
        style={signal ? ANCHOR_VARS : undefined}
      >
        <div ref={frame} className="stage-frame">
          <picture>
            {/* Phones get a square still rendered at phone size, so its station labels stay legible. */}
            {forced ? null : (
              <source
                media="(max-width: 720px) and (prefers-color-scheme: light)"
                srcSet={phonePoster('light')}
              />
            )}
            <source media="(max-width: 720px)" srcSet={phonePoster(forced ?? 'dark')} />
            {forced ? null : (
              <source media="(prefers-color-scheme: light)" srcSet={srcSet('light')} sizes="100vw" />
            )}
            <img
              className="hero-poster"
              src={`/poster/fleet-${forced ?? 'dark'}-1920.webp`}
              srcSet={srcSet(forced ?? 'dark')}
              sizes="100vw"
              alt={posterAlt}
              fetchPriority="high"
              width={1920}
              height={1080}
              aria-hidden={ready ? true : undefined}
            />
          </picture>
          <div ref={host} className="hero-live" data-ready={ready} aria-hidden={!interactive} />
        </div>
        {signal ? (
          <span className="beacon" aria-hidden="true">
            <span className="beacon-beam" />
            <span className="beacon-ring" />
            <span className="beacon-ring beacon-ring-2" />
            <span className="beacon-core" />
          </span>
        ) : null}
      </div>
    </>
  );
}
