// GENERATED by scripts/build-icons.mjs from icons/*.svg. Do not edit by hand.
/** Halyard icon set: 20x20, 1.5 stroke, round caps, currentColor. Inline as innerHTML or a data URI. */
export const icons = {
  agent:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="2.5"/><path d="M5.75 5.5a6.25 6.25 0 0 0 0 9"/><path d="M14.25 5.5a6.25 6.25 0 0 1 0 9"/></svg>',
  alert:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M8.7 3.75a1.5 1.5 0 0 1 2.6 0l5.6 9.75a1.5 1.5 0 0 1-1.3 2.25H4.4a1.5 1.5 0 0 1-1.3-2.25z"/><path d="M10 8v3.25"/><circle cx="10" cy="13.4" r="1" fill="currentColor" stroke="none"/></svg>',
  army: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="6.5" r="2"/><circle cx="14" cy="6.5" r="2"/><circle cx="10" cy="14" r="2"/><path d="M8 6.5h4"/><path d="M7 8.25l2 4"/><path d="M13 8.25l-2 4"/></svg>',
  bell: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5.25 13.5V9a4.75 4.75 0 0 1 9.5 0v4.5l1.25 1.75H4z"/><path d="M8.5 17.5h3"/></svg>',
  blocked:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="6.5"/><path d="M5.4 5.4l9.2 9.2"/></svg>',
  check:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 10.5 8 14l7.5-8"/></svg>',
  chevron:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M8 5.5 12.5 10 8 14.5"/></svg>',
  ci: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 10a6 6 0 0 1-10.4 4.1"/><path d="M4 10a6 6 0 0 1 10.4-4.1"/><path d="M14.75 3.25v3h-3"/><path d="M5.25 16.75v-3h3"/></svg>',
  close:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5.5 5.5l9 9"/><path d="M14.5 5.5l-9 9"/></svg>',
  command:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12.5 5.5v9a2.25 2.25 0 1 0 2.25-2.25h-9.5a2.25 2.25 0 1 0 2.25 2.25v-9a2.25 2.25 0 1 0-2.25 2.25h9.5a2.25 2.25 0 1 0-2.25-2.25"/></svg>',
  cost: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="6.5"/><path d="M12 7.75H9.25a1.25 1.25 0 0 0 0 2.5h1.5a1.25 1.25 0 0 1 0 2.5H8"/><path d="M10 6.25v1.5"/><path d="M10 12.75v1"/></svg>',
  deploy:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M10 12.5V3.5"/><path d="M6.75 6.75 10 3.5l3.25 3.25"/><path d="M3.5 12v2.5A1.5 1.5 0 0 0 5 16h10a1.5 1.5 0 0 0 1.5-1.5V12"/></svg>',
  external:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M8.5 4.5h-3A1.5 1.5 0 0 0 4 6v8.5A1.5 1.5 0 0 0 5.5 16H14a1.5 1.5 0 0 0 1.5-1.5v-3"/><path d="M11.5 4H16v4.5"/><path d="M16 4l-7 7"/></svg>',
  filter:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3.5 5.5h13"/><path d="M6 10h8"/><path d="M8.5 14.5h3"/></svg>',
  fleet:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M10 3.5 12.5 8.5h-5z"/><path d="M5 9.5 7.5 14.5h-5z"/><path d="M15 9.5 17.5 14.5h-5z"/><path d="M4 17h12"/></svg>',
  live: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="1.6" fill="currentColor" stroke="none"/><path d="M6.75 6.75a4.6 4.6 0 0 0 0 6.5"/><path d="M13.25 6.75a4.6 4.6 0 0 1 0 6.5"/><path d="M4.25 4.25a8.1 8.1 0 0 0 0 11.5"/><path d="M15.75 4.25a8.1 8.1 0 0 1 0 11.5"/></svg>',
  merge:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="4.75" r="1.75"/><circle cx="6" cy="15.25" r="1.75"/><circle cx="14" cy="10" r="1.75"/><path d="M6 6.5v7"/><path d="M6 6.5c0 2.5 2.25 3.5 6.25 3.5"/></svg>',
  moon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 12.25A6.5 6.5 0 0 1 7.75 4a6.5 6.5 0 1 0 8.25 8.25z"/></svg>',
  offline:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7.25a10 10 0 0 1 3-1.85"/><path d="M10 5a10 10 0 0 1 7 2.25"/><path d="M6 10.25a6 6 0 0 1 2-1"/><path d="M13.25 9.6a6 6 0 0 1 .75.65"/><path d="M3.5 3.5l13 13"/><circle cx="10" cy="14.5" r="1" fill="currentColor" stroke="none"/></svg>',
  pause:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 4.5v11"/><path d="M13 4.5v11"/></svg>',
  pennant:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5 17.5v-15"/><path d="M5 3.25l10.5 3.5L5 10.25"/></svg>',
  phone:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="5.5" y="2.5" width="9" height="15" rx="2"/><path d="M9 14.75h2"/></svg>',
  play: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6.5 4.5v11a.5.5 0 0 0 .76.43l8.5-5.5a.5.5 0 0 0 0-.86l-8.5-5.5a.5.5 0 0 0-.76.43z"/></svg>',
  project:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3.5 6A1.5 1.5 0 0 1 5 4.5h3l1.75 2h5.25A1.5 1.5 0 0 1 16.5 8v6.5A1.5 1.5 0 0 1 15 16H5a1.5 1.5 0 0 1-1.5-1.5z"/></svg>',
  release:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3.5 4.5v5l7 7 6-6-7-7h-5a1 1 0 0 0-1 1z"/><circle cx="7.25" cy="7.25" r="1.1" fill="currentColor" stroke="none"/></svg>',
  replay:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 10a6 6 0 1 0 1.76-4.24"/><path d="M4.25 3.25v3h3"/><path d="M8.75 7.75v4.5l3.75-2.25z"/></svg>',
  review:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2.5 10S5.25 5 10 5s7.5 5 7.5 5-2.75 5-7.5 5-7.5-5-7.5-5z"/><circle cx="10" cy="10" r="2.25"/></svg>',
  search:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="9" r="5"/><path d="M12.75 12.75 16.5 16.5"/></svg>',
  session:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="14" height="12" rx="2"/><path d="M6.5 8.25 8.5 10.25 6.5 12.25"/><path d="M10.5 12.25h3"/></svg>',
  settings:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3.5 6h7"/><path d="M15 6h1.5"/><path d="M3.5 14H5"/><path d="M9 14h7.5"/><circle cx="13" cy="6" r="2"/><circle cx="7" cy="14" r="2"/></svg>',
  spark:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 14.5l3-4 3 2 4-6 4 3"/></svg>',
  sun: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="3"/><path d="M10 2.5V4"/><path d="M10 16v1.5"/><path d="M2.5 10H4"/><path d="M16 10h1.5"/><path d="M4.7 4.7l1.06 1.06"/><path d="M14.24 14.24l1.06 1.06"/><path d="M4.7 15.3l1.06-1.06"/><path d="M14.24 5.76l1.06-1.06"/></svg>',
  task: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3.5" y="3.5" width="13" height="13" rx="2"/><path d="M6.75 10.25 8.75 12.25 13.25 7.75"/></svg>',
  token:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M10 2.75 16.25 6.4v7.2L10 17.25 3.75 13.6V6.4z"/><circle cx="10" cy="10" r="1.25" fill="currentColor" stroke="none"/></svg>',
  undo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 8H13a3.5 3.5 0 0 1 0 7H9"/><path d="M9.5 5.5 7 8l2.5 2.5"/></svg>',
  waiting:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="6.5"/><path d="M10 6.5V10l2.5 1.75"/></svg>',
  worktree:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="4.75" r="1.75"/><circle cx="6" cy="15.25" r="1.75"/><circle cx="14" cy="6.75" r="1.75"/><path d="M6 6.5v7"/><path d="M14 8.5v.5a3 3 0 0 1-3 3H9a3 3 0 0 0-3 3"/></svg>',
  x: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="6.5"/><path d="M7.75 7.75l4.5 4.5"/><path d="M12.25 7.75l-4.5 4.5"/></svg>',
} as const;
export type IconName = keyof typeof icons;
export const ICON_NAMES = Object.keys(icons) as IconName[];
